PHPリバーシプロジェクト: ReversiPlay Class Reference
ReversiPlay Class Reference
リバーシプレイクラス
Public Member Functions
getmReversi ()
setmReversi ($_mReversi)
getmSetting ()
setmSetting ($_mSetting)
getmCurColor ()
setmCurColor ($_mCurColor)
getmCpu ()
setmCpu ($_mCpu)
getmEdge ()
setmEdge ($_mEdge)
getmPassEnaB ()
setmPassEnaB ($_mPassEnaB)
getmPassEnaW ()
setmPassEnaW ($_mPassEnaW)
getmGameEndSts ()
setmGameEndSts ($_mGameEndSts)
getmPlayLock ()
setmPlayLock ($_mPlayLock)
getViewMsgDlg ()
setViewMsgDlg ($_viewMsgDlg)
getDrawSingle ()
setDrawSingle ($_drawSingle)
getCurColMsg ()
setCurColMsg ($_curColMsg)
getCurStsMsg ()
setCurStsMsg ($_curStsMsg)
getWait ()
setWait ($_wait)
__construct ()
コンストラクタ
__destruct ()
デストラクタ
__sleep ()
シリアライズ
reversiPlay ($y, $x)
リバーシプレイ
reversiPlaySub ($cpuEna, $tmpCol)
リバーシプレイサブ
reversiPlayEnd ()
リバーシプレイ終了
reversiPlayPass ($color)
リバーシプレイパス
reversiPlayCpu ($color, $cpuEna)
リバーシプレイコンピューター
drawUpdate ($assist)
マス描画更新
drawUpdateForcibly ($assist)
マス描画強制更新
reset ()
リセット処理
gameEndAnimExec ()
ゲーム終了アニメーション
sendDrawMsg ($y, $x)
描画メッセージ送信
sendDrawInfoMsg ($y, $x)
情報描画メッセージ送信
Private Member Functions
execMessage ($what, $obj)
メッセージ
ViewMsgDlgLocal ($title, $msg)
メッセージダイアログ
DrawSingleLocal ($y, $x, $sts, $bk, $text)
1マス描画
CurColMsgLocal ($text)
現在の色メッセージ
CurStsMsgLocal ($text)
現在のステータスメッセージ
WaitLocal ($time)
ウェイト
Private Attributes
$_mReversi
リバーシクラス
$_mSetting
リバーシ設定クラス
$_mCurColor
現在の色
$_mCpu
CPU用ワーク
$_mEdge
CPU用角マスワーク
$_mPassEnaB
黒のパス有効フラグ
$_mPassEnaW
白のパス有効フラグ
$_mGameEndSts
ゲーム終了ステータス
$_mPlayLock
プレイロック
$_viewMsgDlg
メッセージコールバック
$_drawSingle
描画コールバック
$_curColMsg
現在の色メッセージコールバック
$_curStsMsg
現在のステータスメッセージコールバック
$_wait
ウェイトコールバック
Detailed Description
リバーシプレイクラス
Definition at line 29 of file ReversiPlay.php.
Constructor & Destructor Documentation
__construct()
__construct ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 100 of file ReversiPlay.php.
__destruct()
__destruct ()
デストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 146 of file ReversiPlay.php.
Member Function Documentation
__sleep()
__sleep ()
シリアライズ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 158 of file ReversiPlay.php.
CurColMsgLocal()
CurColMsgLocal ($text) private
現在の色メッセージ
Parameters
[in] $text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 981 of file ReversiPlay.php.
Referenced by execMessage().
CurStsMsgLocal()
CurStsMsgLocal ($text) private
現在のステータスメッセージ
Parameters
[in] $text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 998 of file ReversiPlay.php.
Referenced by execMessage().
DrawSingleLocal()
DrawSingleLocal ($y, $x, $sts, $bk, $text) private
1マス描画
Parameters
[in] $y Y座標
[in] $x X座標
[in] $sts ステータス
[in] $bk 背景
[in] $text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 964 of file ReversiPlay.php.
Referenced by execMessage().
drawUpdate()
drawUpdate ($assist)
マス描画更新
Parameters
[in] $assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 638 of file ReversiPlay.php.
Referenced by reversiPlay(), and reversiPlayCpu().
drawUpdateForcibly()
drawUpdateForcibly ($assist)
マス描画強制更新
Parameters
[in] $assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 671 of file ReversiPlay.php.
Referenced by reset().
execMessage()
execMessage ($what, $obj) private
メッセージ
Parameters
[in] $what
[in] $obj
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 849 of file ReversiPlay.php.
Referenced by drawUpdate(), drawUpdateForcibly(), gameEndAnimExec(), reset(), reversiPlay(), reversiPlayCpu(), reversiPlayEnd(), sendDrawInfoMsg(), and sendDrawMsg().
gameEndAnimExec()
gameEndAnimExec ()
ゲーム終了アニメーション
Returns
ウェイト時間
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 746 of file ReversiPlay.php.
Referenced by reversiPlayEnd().
reset()
reset ()
リセット処理
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 696 of file ReversiPlay.php.
reversiPlay()
reversiPlay ($y, $x)
リバーシプレイ
Parameters
[in] $y $y座標
[in] $x $x座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 183 of file ReversiPlay.php.
reversiPlayCpu()
reversiPlayCpu ($color, $cpuEna)
リバーシプレイコンピューター
Parameters
[in] $color CPU色
[in] $cpuEna CPU有効フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 380 of file ReversiPlay.php.
Referenced by reversiPlaySub().
reversiPlayEnd()
reversiPlayEnd ()
リバーシプレイ終了
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 307 of file ReversiPlay.php.
Referenced by reversiPlay(), and reversiPlaySub().
reversiPlayPass()
reversiPlayPass ($color)
リバーシプレイパス
Parameters
[in] $color パス色
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 358 of file ReversiPlay.php.
Referenced by reversiPlay(), and reversiPlaySub().
reversiPlaySub()
reversiPlaySub ($cpuEna, $tmpCol)
リバーシプレイサブ
Parameters
[in] $cpuEna
[in] $tmpCol
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 277 of file ReversiPlay.php.
Referenced by reversiPlay().
sendDrawInfoMsg()
sendDrawInfoMsg ($y, $x)
情報描画メッセージ送信
Parameters
[in] $y Y座標
[in] $x X座標
Returns
ありません
Date
2018.03.02
Definition at line 830 of file ReversiPlay.php.
Referenced by drawUpdate().
sendDrawMsg()
sendDrawMsg ($y, $x)
描画メッセージ送信
Parameters
[in] $y Y座標
[in] $x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 812 of file ReversiPlay.php.
Referenced by drawUpdate(), gameEndAnimExec(), reversiPlay(), and reversiPlayCpu().
ViewMsgDlgLocal()
ViewMsgDlgLocal ($title, $msg) private
メッセージダイアログ
Parameters
[in] $title タイトル
[in] $msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 943 of file ReversiPlay.php.
Referenced by reversiPlay(), reversiPlayEnd(), and reversiPlayPass().
WaitLocal()
WaitLocal ($time) private
ウェイト
Parameters
[in] $time ウェイト時間(msec)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1015 of file ReversiPlay.php.
Referenced by drawUpdate(), gameEndAnimExec(), reversiPlay(), and reversiPlayEnd().
The documentation for this class was generated from the following file:
Model/ReversiPlay.php