PHPリバーシプロジェクト: Reversi Class Reference
Reversi Class Reference
リバーシクラス
Public Member Functions
getmMasuSts ()
setmMasuSts ($_mMasuSts)
getmMasuStsOld ()
setmMasuStsOld ($_mMasuStsOld)
getmMasuStsEnaB ()
setmMasuStsEnaB ($_mMasuStsEnaB)
getmMasuStsCntB ()
setmMasuStsCntB ($_mMasuStsCntB)
getmMasuStsPassB ()
setmMasuStsPassB ($_mMasuStsPassB)
getmMasuStsAnzB ()
setmMasuStsAnzB ($_mMasuStsAnzB)
getmMasuPointB ()
setmMasuPointB ($_mMasuPointB)
getmMasuPointCntB ()
setmMasuPointCntB ($_mMasuPointCntB)
getmMasuBetCntB ()
setmMasuBetCntB ($_mMasuBetCntB)
getmMasuStsEnaW ()
setmMasuStsEnaW ($_mMasuStsEnaW)
getmMasuStsCntW ()
setmMasuStsCntW ($_mMasuStsCntW)
getmMasuStsPassW ()
setmMasuStsPassW ($_mMasuStsPassW)
getmMasuStsAnzW ()
setmMasuStsAnzW ($_mMasuStsAnzW)
getmMasuPointW ()
setmMasuPointW ($_mMasuPointW)
getmMasuPointCntW ()
setmMasuPointCntW ($_mMasuPointCntW)
getmMasuBetCntW ()
setmMasuBetCntW ($_mMasuBetCntW)
getmMasuCnt ()
setmMasuCnt ($_mMasuCnt)
getmMasuCntMax ()
setmMasuCntMax ($_mMasuCntMax)
getmMasuHistCur ()
setmMasuHistCur ($_mMasuHistCur)
getmMasuHist ()
setmMasuHist ($_mMasuHist)
__construct ($masuCnt, $masuMax)
コンストラクタ
__destruct ()
デストラクタ
reset ()
リセット
AnalysisReversi ($bPassEna, $wPassEna)
解析を行う
getMasuSts ($y, $x)
マスステータスを取得
getMasuStsOld ($y, $x)
以前のマスステータスを取得
getMasuStsEna ($color, $y, $x)
指定座標に指定色を置けるかチェック
getMasuStsCnt ($color, $y, $x)
指定座標の獲得コマ数取得
getColorEna ($color)
指定色が現在置ける場所があるかチェック
getGameEndSts ()
ゲーム終了かチェック
setMasuSts ($color, $y, $x)
指定座標にコマを置く
setMasuStsForcibly ($color, $y, $x)
指定座標にコマを強制的に置く
setMasuCnt ($cnt)
マスの数変更
getPoint ($color, $num)
ポイント座標取得
getPointCnt ($color)
ポイント座標数取得
getBetCnt ($color)
コマ数取得
getPassEna ($color, $y, $x)
パス判定
getHistory ($num)
履歴取得
getHistoryCnt ()
履歴数取得
getPointAnz ($color, $y, $x)
ポイント座標解析取得
checkEdge ($color, $y, $x)
角の隣に置いても角を取られないマス検索
getEdgeSideZero ($y, $x)
指定座標が角か取得
getEdgeSideOne ($y, $x)
指定座標が角の一つ手前か取得
getEdgeSideTwo ($y, $x)
指定座標が角の二つ手前か取得
getEdgeSideThree ($y, $x)
指定座標が角の三つ以上手前か取得
Private Member Functions
makeMasuSts ($color)
各コマの置ける場所等のステータス作成
revMasuSts ($color, $y, $x)
コマをひっくり返す
checkPara ($para, $min, $max)
パラメーター範囲チェック
AnalysisReversiBlack ()
解析を行う(黒)
AnalysisReversiWhite ()
解析を行う(白)
Private Attributes
$_mMasuSts
マスの状態
$_mMasuStsOld
以前のマスの状態
$_mMasuStsEnaB
黒の置ける場所
$_mMasuStsCntB
黒の獲得コマ数
$_mMasuStsPassB
黒が相手をパスさせる場所
$_mMasuStsAnzB
黒がその場所に置いた場合の解析結果
$_mMasuPointB
黒の置ける場所座標一覧
$_mMasuPointCntB
黒の置ける場所座標一覧数
$_mMasuBetCntB
黒コマ数
$_mMasuStsEnaW
白の置ける場所
$_mMasuStsCntW
白の獲得コマ数
$_mMasuStsPassW
白が相手をパスさせる場所
$_mMasuStsAnzW
白がその場所に置いた場合の解析結果
$_mMasuPointW
白の置ける場所座標一覧
$_mMasuPointCntW
白の置ける場所座標一覧数
$_mMasuBetCntW
白コマ数
$_mMasuCnt
縦横マス数
$_mMasuCntMax
縦横マス最大数
$_mMasuHistCur
履歴現在位置
$_mMasuHist
履歴
Detailed Description
リバーシクラス
Definition at line 30 of file Reversi.php.
Constructor & Destructor Documentation
__construct()
__construct ($masuCnt, $masuMax)
コンストラクタ
Parameters
[in] $masuCnt 縦横マス数
[in] $masuMax 縦横マス最大数
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 127 of file Reversi.php.
__destruct()
__destruct ()
デストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 200 of file Reversi.php.
Member Function Documentation
AnalysisReversi()
void AnalysisReversi ($bPassEna, $wPassEna)
解析を行う
Parameters
[in] $bPassEna 1=黒パス有効
[in] $wPassEna 1=白パス有効
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 950 of file Reversi.php.
AnalysisReversiBlack()
AnalysisReversiBlack () private
解析を行う(黒)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 638 of file Reversi.php.
Referenced by AnalysisReversi().
AnalysisReversiWhite()
AnalysisReversiWhite () private
解析を行う(白)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 793 of file Reversi.php.
Referenced by AnalysisReversi().
checkEdge()
checkEdge ($color, $y, $x)
角の隣に置いても角を取られないマス検索
Parameters
[in] $color コマ色
[in] $y マスの$y座標
[in] $x マスの$x座標
Returns
0 : 取られる それ以外 : 取られない
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1313 of file Reversi.php.
Referenced by AnalysisReversiBlack(), and AnalysisReversiWhite().
checkPara()
checkPara ($para, $min, $max) private
パラメーター範囲チェック
Parameters
[in] $para チェックパラメーター
[in] $min パラメーター最小値
[in] $max パラメーター最大値
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 623 of file Reversi.php.
Referenced by getHistory(), getMasuSts(), getMasuStsCnt(), getMasuStsEna(), getMasuStsOld(), getPassEna(), getPoint(), getPointAnz(), and setMasuCnt().
getBetCnt()
getBetCnt ($color)
コマ数取得
Parameters
[in] $color コマ色
Returns
コマ数取得
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1216 of file Reversi.php.
getColorEna()
getColorEna ($color)
指定色が現在置ける場所があるかチェック
Parameters
[in] $color コマ色
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1065 of file Reversi.php.
Referenced by AnalysisReversiBlack(), AnalysisReversiWhite(), and getGameEndSts().
getEdgeSideOne()
getEdgeSideOne ($y, $x)
指定座標が角の一つ手前か取得
Parameters
[in] $y $y座標
[in] $x $x座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1455 of file Reversi.php.
Referenced by AnalysisReversiBlack(), and AnalysisReversiWhite().
getEdgeSideThree()
getEdgeSideThree ($y, $x)
指定座標が角の三つ以上手前か取得
Parameters
[in] $y $y座標
[in] $x $x座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1519 of file Reversi.php.
Referenced by AnalysisReversiBlack(), and AnalysisReversiWhite().
getEdgeSideTwo()
getEdgeSideTwo ($y, $x)
指定座標が角の二つ手前か取得
Parameters
[in] $y $y座標
[in] $x $x座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1487 of file Reversi.php.
Referenced by AnalysisReversiBlack(), and AnalysisReversiWhite().
getEdgeSideZero()
getEdgeSideZero ($y, $x)
指定座標が角か取得
Parameters
[in] $y $y座標
[in] $x $x座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1431 of file Reversi.php.
Referenced by AnalysisReversiBlack(), and AnalysisReversiWhite().
getGameEndSts()
getGameEndSts ()
ゲーム終了かチェック
Returns
0 : 続行 それ以外 : ゲーム終了
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1087 of file Reversi.php.
getHistory()
getHistory ($num)
履歴取得
Parameters
[in] $num ポイント
Returns
履歴 NULL : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1257 of file Reversi.php.
getHistoryCnt()
getHistoryCnt ()
履歴数取得
Returns
履歴数
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1274 of file Reversi.php.
getMasuSts()
getMasuSts ($y, $x)
マスステータスを取得
Parameters
[in] $y 取得するマスのY座標
[in] $x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 990 of file Reversi.php.
Referenced by checkEdge().
getMasuStsCnt()
getMasuStsCnt ($color, $y, $x)
指定座標の獲得コマ数取得
Parameters
[in] $color コマ色
[in] $y マスの$y座標
[in] $x マスの$x座標
Returns
-1 : 失敗 それ以外 : 獲得コマ数
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1046 of file Reversi.php.
getMasuStsEna()
getMasuStsEna ($color, $y, $x)
指定座標に指定色を置けるかチェック
Parameters
[in] $color コマ色
[in] $y マスの$y座標
[in] $x マスの$x座標
Returns
1 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1025 of file Reversi.php.
Referenced by AnalysisReversiBlack(), AnalysisReversiWhite(), getColorEna(), and setMasuSts().
getMasuStsOld()
getMasuStsOld ($y, $x)
以前のマスステータスを取得
Parameters
[in] y 取得するマスのY座標
[in] x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1007 of file Reversi.php.
getPassEna()
getPassEna ($color, $y, $x)
パス判定
Parameters
[in] $color コマ色
[in] $y マスのY座標
[in] $x マスのX座標
Returns
パス判定
0 : NOT PASS
1 : PASS
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1238 of file Reversi.php.
getPoint()
getPoint ($color, $num)
ポイント座標取得
Parameters
[in] $color コマ色
[in] $num ポイント
Returns
ポイント座標 NULL : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1180 of file Reversi.php.
getPointAnz()
getPointAnz ($color, $y, $x)
ポイント座標解析取得
Parameters
[in] $color コマ色
[in] $y マスの$y座標
[in] $x マスの$x座標
Returns
ポイント座標解析 NULL : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1292 of file Reversi.php.
getPointCnt()
getPointCnt ($color)
ポイント座標数取得
Parameters
[in] $color コマ色
Returns
ポイント座標数取得
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1199 of file Reversi.php.
Referenced by AnalysisReversiBlack(), and AnalysisReversiWhite().
makeMasuSts()
makeMasuSts ($color) private
各コマの置ける場所等のステータス作成
Parameters
[in] $color ステータスを作成するコマ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 241 of file Reversi.php.
Referenced by AnalysisReversi(), AnalysisReversiBlack(), AnalysisReversiWhite(), reset(), and setMasuSts().
reset()
reset ()
リセット
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 212 of file Reversi.php.
Referenced by __construct(), and setMasuCnt().
revMasuSts()
revMasuSts ($color, $y, $x) private
コマをひっくり返す
Parameters
[in] $color ひっくり返す元コマ
[in] $y ひっくり返す元コマの$y座標
[in] $x ひっくり返す元コマの$x座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 447 of file Reversi.php.
Referenced by AnalysisReversiBlack(), AnalysisReversiWhite(), and setMasuSts().
setMasuCnt()
setMasuCnt ($cnt)
マスの数変更
Parameters
[in] $cnt マスの数
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1155 of file Reversi.php.
setMasuSts()
setMasuSts ($color, $y, $x)
指定座標にコマを置く
Parameters
[in] $color コマ色
[in] $y マスの$y座標
[in] $x マスの$x座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1106 of file Reversi.php.
setMasuStsForcibly()
setMasuStsForcibly ($color, $y, $x)
指定座標にコマを強制的に置く
Parameters
[in] $color コマ色
[in] $y マスの$y座標
[in] $x マスの$x座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.03.02
Definition at line 1138 of file Reversi.php.
The documentation for this class was generated from the following file:
Model/Reversi.php